# Generated by Django 4.0.6 on 2022-08-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelTable(
            name='instructor',
            table='Instructor',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
