# Generated by Django 4.0.6 on 2022-08-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0002_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='a',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='b',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='c',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='d',
        ),
    ]
