# Generated by Django 4.0.6 on 2022-08-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
