# Generated by Django 4.0.6 on 2022-08-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='course',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='posted_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
